from setuptools import setup

setup(name='playground',
      packages=['playground'],
      install_requires=[
          # 'gym[mujoco,atari,classic_control,robotics]',
          'mujoco-py',
          'gym',
          'baselines',
          'params_proto',
          'ml-logger',
          'moleskin',
          'visdom',
          'scipy',
          'tqdm',
          'joblib',
          'zmq',
          'dill',
          'progressbar2',
          'mpi4py',
          'cloudpickle',
          'tensorflow>=1.4.0',
          'click',
      ],
      description='A Playground for RL and Robotics Environments',
      author='Ge Yang',
      url='https://github.com/episodeyang/rl-playground',
      author_email='yangge1987@gmail.com',
      version='0.0.0')
